In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# ques_path = '../68a58892b4058539485342/questions_public.xlsx'
ques_path = '../68a86b9f5d944822407386.xlsx'

df = pd.read_excel(ques_path)

In [3]:
pd.options.display.max_colwidth = 150

df.head(15)

,id,block,full_question,answer_type
0,1,Both,"По какому адресу зарегистрирован АО ""ЛОТТЕ Рахат""?",str
1,2,Both,"Какие цели устойчивого развития ООН являются приоритетными для АО ""Казахтелеком""? Перечислите номера этих целей через запятую",str
2,3,OCR,"Какая была выручка у АО ""Кеденстранссервис"" за 2024 год (в млрд тенге, округляя до 2-х знаков после запятой)?",float
3,4,AR,Какое у Казахстан Темир Жолы фактическое значение по показателю рентабельности среднего задействованного капитала (в %) в 2023 году?,float
4,5,OCR,Сколько тонн составили прямые выбросы СО2 с месторождения Матин в 2024 году (округляя до 2-х знаков после запятой)?,float
5,6,AR,"Какая аудиторская компания проводила аудит финансовой отчетности АО ""Teniz Capital Investment Banking"" в 2024 году?",str
6,7,OCR,"Согласно ключевым ценовым отметкам золота в отчете BASS Gold, сколько составила средняя цена за унцию в 4-м квартале 2024 года?",int
7,8,OCR,"Какую сумму составила валовая прибыль ТОО “Компания Фаэтон” за 2024 год (млн тенге, округляя до 2-х знаков после запятой)?",float
8,9,AR,Сколько вертолетов есть у компании Air Astana?,int
9,10,Both,В среднем сколько маршрутов есть на каждую из стран-направлений у всей группы Air Astana (округляя до 2-х знаков после запятой)?,float
10,11,Both,"Сколько наименований различной продукции выпускает АО ""ЛОТТЕ Рахат""?",int
11,12,OCR,Какую сумму составили расходы связанные с износом за 2024 год у АО “Матен Петролеум”(тыс тенге)?,int
12,13,Both,Какая компания проводила аудит годовой отчетности АО “Банк Развития Казахстана” за 2024 год?,str
13,14,OCR,Какой процент у города Уральск в реализации продукции АО “Баян Сулу” в 2024 году (округляя до 2-х знаков после запятой)?,float
14,15,OCR,"На какую сумму у АО ""АзияАгроФуд"" есть нефинансовые обязательства (в тыс. тенге)?",int

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             200 non-null    int64
 1   block          200 non-null    object
 2   full_question  200 non-null    object
 3   answer_type    200 non-null    object
dtypes: int64(1), object(3)
memory usage: 6.4+ KB

In [18]:
# id_ = 197 # success
# id_ = 194 # success
# id_ = 171
# id_ = 196
# id_ = 185 # fail
# id_ = 182 # success
# id_ = 11 # success
id_ = 200


df[df["id"] == id_]

,id,block,full_question,answer_type
199,200,Both,Какова суммарная доля участия членов Совета Директоров в АО “Баян Сулу” (округляя до 2-х знаков после запятой)?,float

In [6]:
for index, row in df.iterrows():
    print(index)
    print(row)

0
id                                                                                    1
block                                                                               OCR
full_question    Какой организацией представлен АО «НК Қазақстан Темір Жолы» в Венгрии?
answer_type                                                                         str
Name: 0, dtype: object
1
id                                                                                2
block                                                                           OCR
full_question    Какая цель у КТЖ по показателю (в баллах) рейтинг ESG на 2032 год?
answer_type                                                                     int
Name: 1, dtype: object
2
id                                                                                                                                                  3
block                                                                                                                                              AR
full_question    Какое у Казахстан Темир Жолы фактическое значение по показателю рентабельности среднего задействованного капитала (в %) в 2024 году?
answer_type                                                                                                                                     float
Name: 2, dtype: object
3
id                                                                                              4
block                                                                                        Both
full_question    В скольких месяцах 2024 года добыча руды превысила 5 млн тонн у ТОО "Bass Gold"?
answer_type                                                                                   int
Name: 3, dtype: object
4
id                                                                    5
block                                                               OCR
full_question    Какую должность занимает Им Вонхёк в АО "ЛОТТЕ Рахат"?
answer_type                                                         str
Name: 4, dtype: object
5
id                                                                                      6
block                                                                                Both
full_question    Сколько физлиц нерезидентов среди аффилированных лиц у АО "ЛОТТЕ Рахат"?
answer_type                                                                           int
Name: 5, dtype: object
6
id                                                                                                       7
block                                                                                                   AR
full_question    У какой компании капитальные затраты были выше: ТОО "Bass Gold" или АО "МАТЕН ПЕТРОЛЕУМ"?
answer_type                                                                                            str
Name: 6, dtype: object
7
id                                                                                                                          8
block                                                                                                                     OCR
full_question    Сколько тенге составляет обязательный размер дивидендов по привелигированным акциям в расчете на одну акцию?
answer_type                                                                                                               int
Name: 7, dtype: object
8
id                                                                                                                               9
block                                                                                                                           AR
full_question    Какая сумма в тенге налоговых убытков была у группы компаний АО «Матен Петролеум» на момент 31 декабря 2024 года?
answer_type                                                                                                                    int
Name: 8, dtype: object
9
id                                                                                     10
block                                                                                Both
full_question    Сколько всего тонн выбросов CO2 произвёл объект НПС Каратон в 2024 году?
answer_type                                                                         float
Name: 9, dtype: object
10
id                                                                                      11
block                                                                                 Both
full_question    Какая еженедельная частота рейсов было в 2024 году у компании FlyArystan?
answer_type                                                                            int
Name: 10, dtype: object
11
id                                                                                  12
block                                                                             Both
full_question    Сколько лет срок полезной службы воздушного судна в учётной политике?
answer_type                                                                        int
Name: 11, dtype: object
12
id                                                                         13
block                                                                     OCR
full_question    Кто является Управляющим директором по финансам АО "НК "ҚТЖ"
answer_type                                                               str
Name: 12, dtype: object
13
id                                                             14
block                                                         OCR
full_question    Кто главный бухгалтер в АО "AsiaAgroFood" (ФИО)?
answer_type                                                   str
Name: 13, dtype: object
14
id                                                                     15
block                                                                  AR
full_question    Сколько работников было в АО "Казахтелеком" в 2024 году?
answer_type                                                           int
Name: 14, dtype: object

In [7]:
row

id                                                                     15
block                                                                  AR
full_question    Сколько работников было в АО "Казахтелеком" в 2024 году?
answer_type                                                           int
Name: 14, dtype: object

In [8]:
row["id"]

15

In [ ]:
ans = "4"
row["answer_type"]

'int'

In [12]:
type_str = "float"
answer = "4"
eval(f"{type_str}('{answer}')")

4.0