In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_excel('../689af43b20634866094170/questions_public.xlsx')

   id block                                      full_question answer_type
0   1   OCR  Какой организацией представлен АО «НК Қазақста...         str
1   2   OCR  Какая цель у КТЖ по показателю (в баллах) рейт...         int
2   3    AR  Какое у Казахстан Темир Жолы фактическое значе...       float
3   4  Both  В скольких месяцах 2024 года добыча руды превы...         int
4   5   OCR  Какую должность занимает Им Вонхёк в АО "ЛОТТЕ...         str

In [4]:
pd.options.display.max_colwidth = 150

df.head()

,id,block,full_question,answer_type
0,1,OCR,Какой организацией представлен АО «НК Қазақстан Темір Жолы» в Венгрии?,str
1,2,OCR,Какая цель у КТЖ по показателю (в баллах) рейтинг ESG на 2032 год?,int
2,3,AR,Какое у Казахстан Темир Жолы фактическое значение по показателю рентабельности среднего задействованного капитала (в %) в 2024 году?,float
3,4,Both,"В скольких месяцах 2024 года добыча руды превысила 5 млн тонн у ТОО ""Bass Gold""?",int
4,5,OCR,"Какую должность занимает Им Вонхёк в АО ""ЛОТТЕ Рахат""?",str

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             15 non-null     int64
 1   block          15 non-null     object
 2   full_question  15 non-null     object
 3   answer_type    15 non-null     object
dtypes: int64(1), object(3)
memory usage: 608.0+ bytes